Repository bcgov/common-hosted-email-service, pull requests merged in 2019-11, with the labels that each got.

#30 Feature/stats tracking
  app/app.js
  app/src/components/health.js
  app/src/components/stackpole.js
  app/src/components/transformer.js
  app/src/components/validators.js
  app/src/middleware/authorizedParty.js
  app/src/middleware/mailApiTracker.js
  app/src/routes/v1.js
  app/src/services/dataConn.js
  app/src/services/dataSvc.js
  app/src/services/migrations/20191105104446_stats.js
  app/src/services/models/statistic.js
  app/src/services/statisticSvc.js
  app/tests/integration/chesSvc.spec.js
  app/tests/integration/dataSvc.spec.js
  app/tests/integration/dataUtils.js
  app/tests/integration/statisticSvc.spec.js
  app/tests/unit/components/stackpole.spec.js
  app/tests/unit/components/transformer.spec.js
Labels: documentation, enhancement

#29 Add /cancel/:msgId support to API
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/src/components/state.js
  app/src/components/transformer.js
  app/src/components/validators.js
  app/src/docs/v1.api-spec.yaml
  app/src/middleware/validation.js
  app/src/routes/v1.js
  app/src/routes/v1/cancel.js
  app/src/routes/v1/email.js
  app/src/routes/v1/health.js
  app/src/routes/v1/status.js
  app/src/services/chesSvc.js
  app/src/services/dataSvc.js
  app/src/services/queueListener.js
  app/src/services/queueSvc.js
  app/tests/integration/chesSvc.spec.js
  app/tests/integration/dataSvc.spec.js
  app/tests/integration/dataUtils.js
  app/tests/integration/statisticSvc.spec.js
  app/tests/unit/components/state.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/cancel.spec.js
Labels: documentation, enhancement

#31 Add /cancel query support to API
  app/bin/www
  app/src/components/validators.js
  app/src/docs/v1.api-spec.yaml
  app/src/middleware/validation.js
  app/src/routes/v1/cancel.js
  app/src/services/chesSvc.js
  app/src/services/dataSvc.js
  app/src/services/queueSvc.js
  app/src/services/statisticSvc.js
  app/tests/integration/chesSvc.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1/cancel.spec.js
  app/tests/unit/routes/v1/merge.spec.js
  app/tests/unit/routes/v1/status.spec.js
Labels: enhancement

#32 Update dependencies in readme
  app/README.md
  app/package-lock.json
  app/package.json
Labels: documentation

#33 Missing cleanup step in readme
  openshift/README.md
Labels: documentation
