Repository bcgov/common-hosted-email-service, pull requests merged in 2019-09, with the labels that each got.

#4 Add Keycloak JWT authentication
  Jenkinsfile
  Jenkinsfile.cicd
  app/app.js
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/package-lock.json
  app/package.json
  app/src/components/email.js
  app/src/components/keycloak.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/checks.js
  app/src/routes/v1/email.js
  app/tests/unit/routes/v1/checks.spec.js
  app/tests/unit/routes/v1/email.spec.js
  openshift/README.md
  openshift/app.dc.yaml
Labels: bug, documentation, enhancement

#5 Add API Usage documentation
  app/README.md
  app/package-lock.json
  app/package.json
  app/src/docs/v1.api-spec.yaml
Labels: documentation

#6 Add cc and bcc fields
  app/src/components/email.js
  app/src/components/utils.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/email.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/components/utils.spec.js
Labels: documentation, enhancement

#10 Add PR checklist for OAS 3.0 spec documentation updates
  .github/pull_request_template.md
Labels: documentation

#9 Add validation on attachments.
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/package.json
  app/src/components/utils.js
  app/src/routes/v1/email.js
  app/tests/unit/components/base64Files.js
  app/tests/unit/components/utils.spec.js
  openshift/README.md
Labels: documentation, enhancement

#11 Update CHES V1 API Specification
  app/src/docs/v1.api-spec.yaml
Labels: documentation

#12 Update validation routines.
  app/package-lock.json
  app/package.json
  app/src/components/utils.js
  app/src/components/validators.js
  app/src/docs/v1.api-spec.yaml
  app/src/middleware/validation.js
  app/src/routes/v1/email.js
  app/tests/unit/components/base64Files.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1/email.spec.js
Labels: enhancement

#8 Add Initial Redis Queueing support
  Jenkinsfile
  Jenkinsfile.cicd
  app/README.md
  app/app.js
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/package-lock.json
  app/package.json
  app/src/components/checks.js
  app/src/components/email.js
  app/src/components/queue.js
  app/src/components/utils.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/email.js
  app/tests/unit/components/checks.spec.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/components/queue.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/email.spec.js
  openshift/README.md
  openshift/app.dc.yaml
  openshift/redis.dc.yaml
  openshift/redis.secret.yaml
Labels: enhancement

#13 Add validation for delayTS.
  app/app.js
  app/package-lock.json
  app/src/components/checks.js
  app/src/components/validators.js
  app/src/middleware/validation.js
  app/tests/unit/components/queue.spec.js
  app/tests/unit/components/validators.spec.js
Labels: bug
