Repository bcgov/common-hosted-email-service, pull requests merged in 2019-10, with the labels that each got.

#15 Add Initial Status endpoint support
  app/src/components/email.js
  app/src/components/health.js
  app/src/components/merge.js
  app/src/components/queue.js
  app/src/components/status.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/email.js
  app/src/routes/v1/health.js
  app/src/routes/v1/merge.js
  app/src/routes/v1/status.js
  app/tests/common/helper.js
  app/tests/fixtures/base64Files.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/components/health.spec.js
  app/tests/unit/components/merge.spec.js
  app/tests/unit/components/queue.spec.js
  app/tests/unit/components/status.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1.spec.js
  app/tests/unit/routes/v1/email.spec.js
  app/tests/unit/routes/v1/health.spec.js
  app/tests/unit/routes/v1/merge.spec.js
  app/tests/unit/routes/v1/status.spec.js
Labels: enhancement

#16 Hotfix: Ensure merge endpoint returns msgId wrapped in an object
  app/src/components/merge.js
Labels: bug

#17 Add and expose delayTS support to API
  app/src/components/merge.js
  app/src/components/status.js
  app/src/components/utils.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1/email.js
  app/tests/unit/components/merge.spec.js
  app/tests/unit/components/status.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/routes/v1/email.spec.js
Labels: documentation, enhancement

#19 Add High Availability Postgres infrastructure support via Patroni
  Jenkinsfile
  Jenkinsfile.cicd
  app/app.js
  app/config/custom-environment-variables.json
  app/config/default.json
  app/config/test.json
  app/package-lock.json
  app/package.json
  openshift/app.dc.yaml
  openshift/patroni-ephemeral.dc.yaml
  openshift/patroni.dc.yaml
  openshift/patroni.secret.yaml
  openshift/redis-ephemeral.dc.yaml
  openshift/redis.dc.yaml
Labels: enhancement

#24 Add cancel endpoints to API specification
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/tests/unit/routes/v1.spec.js
Labels: documentation

#23 Store data in Patroni
  app/app.js
  app/knexfile.js
  app/package-lock.json
  app/package.json
  app/src/components/email.js
  app/src/components/health.js
  app/src/components/merge.js
  app/src/components/queue.js
  app/src/components/status.js
  app/src/components/validators.js
  app/src/middleware/authorizedParty.js
  app/src/middleware/validation.js
  app/src/routes/v1.js
  app/src/routes/v1/email.js
  app/src/routes/v1/merge.js
  app/src/routes/v1/status.js
  app/src/services/chesSvc.js
  app/src/services/dataConn.js
  app/src/services/dataSvc.js
  app/src/services/emailConn.js
  app/src/services/emailSvc.js
  app/src/services/migrations/20191016164716_init.js
  app/src/services/models/message.js
  app/src/services/models/mixins.js
  app/src/services/models/queue.js
  app/src/services/models/status.js
  app/src/services/models/trxn.js
  app/src/services/queueConn.js
  app/src/services/queueListener.js
  app/src/services/queueSvc.js
  app/src/services/transform.js
  app/tests/fixtures/base64Files.js
  app/tests/integration/chesSvc.spec.js
  app/tests/integration/dataSvc.spec.js
  app/tests/integration/dataUtils.js
  app/tests/unit/components/email.spec.js
  app/tests/unit/components/health.spec.js
  app/tests/unit/components/merge.spec.js
  app/tests/unit/components/queue.spec.js
  app/tests/unit/components/status.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1/email.spec.js
  app/tests/unit/routes/v1/merge.spec.js
  app/tests/unit/routes/v1/status.spec.js
  openshift/app.dc.yaml
  sonar-project.properties
Labels: enhancement

#25 Update /status/:msgId and /health to reflect API specification changes
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/components/validators.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/status.js
  app/src/services/chesSvc.js
  app/src/services/dataConn.js
  app/src/services/dataSvc.js
  app/src/services/queueConn.js
  app/src/services/transform.js
  app/tests/unit/routes/v1/status.spec.js
Labels: enhancement

#26 Add Status Query endpoint support
  app/package.json
  app/src/components/transformer.js
  app/src/components/utils.js
  app/src/components/validators.js
  app/src/docs/v1.api-spec.yaml
  app/src/middleware/validation.js
  app/src/routes/v1/email.js
  app/src/routes/v1/merge.js
  app/src/routes/v1/status.js
  app/src/services/chesSvc.js
  app/src/services/dataSvc.js
  app/src/services/emailSvc.js
  app/src/services/transform.js
  app/tests/integration/chesSvc.spec.js
  app/tests/unit/components/health.spec.js
  app/tests/unit/components/transformer.spec.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/components/validators.spec.js
  app/tests/unit/routes/v1/email.spec.js
  app/tests/unit/routes/v1/merge.spec.js
  app/tests/unit/routes/v1/status.spec.js
Labels: documentation, enhancement

#27 Bugfix non-default columns were not being returned for status query
  app/src/services/dataSvc.js
Labels: bug
