Repository bcgov/common-hosted-email-service, pull requests merged in 2020-08, with the labels that each got.

#47 upgrade dot-prop to version 5.1.1 or later
  app/package-lock.json
Labels: dependencies

#49 Mass npm package updates
  app/package-lock.json
  app/package.json
  app/src/services/dataSvc.js
  app/tests/integration/chesSvc.spec.js
  app/tests/integration/dataSvc.spec.js
  app/tests/integration/statisticSvc.spec.js
Labels: bug, dependencies

#52 Update Objection queries to use non-deprecated Graph API
  app/package-lock.json
  app/package.json
  app/src/services/dataSvc.js
Labels: bug, dependencies

#53 Change DB Connection probe to detect read-only state
  app/src/services/dataConn.js
Labels: bug
